Repository titanscouting/tra-analysis, pull requests merged in 2020-10, with the labels that each got.

#48 Make QOL changes to README
  README.md
Labels: enhancement, help wanted

#52 Moved meta files to .github folder, added PR template
  .github/CONTRIBUTING.md
  .github/LICENSE
  .github/MAINTAINERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/README.md
  .github/SECURITY.md
Labels: enhancement

#59 Fixes for issue #58
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: bug-fix

#60 Fixed test_analysis.py
  analysis-master/test_analysis.py
  analysis-master/tra_analysis/Sort.py
  analysis-master/tra_analysis/__init__.py
Labels: bug-fix
